[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ccxt>=4.4.86",
    "pandas>=2.2.3",
    "pandas-ta>=0.3.14b0",
    "requests>=2.32.3",
    "telegram>=0.0.1",
]
